### ISSUE TITLE
Enhancement: download queries for SDSS filters

### ISSUE THREAD

**Issue by bmorris3** [tcjansen/GSoC#1]
Enhancement proposal: ultimately you'll be making a PR to astroquery which queries the [VO service from the SVO Filter Profile Service](http://svo2.cab.inta-csic.es/theory/fps/index.php?mode=voservice) 🌈 , but for now, you can do something simpler to retrieve the filter response curves for Sloan filters. Use the `astropy.utils.data.download_file` function to grab the response curves for each filter from the following links (and remove the step in the tutorial which says 'you can download the filter response curves here...'). The goal here is to avoid including any data files in the PR or requiring the user to manually download something which can be done in the code. 
* [SDSS r](http://svo2.cab.inta-csic.es/theory/fps/getdata.php?format=ascii&id=SLOAN/SDSS.r)
* [SDSS z](http://svo2.cab.inta-csic.es/theory/fps/getdata.php?format=ascii&id=SLOAN/SDSS.z)

**Comment by tcjansen** [comment]
Woah, so upon implementing download_file (which works well, yay), I noticed that the SDSS transmissions from SVO are much different from those provided by APO... Is this due to some physical difference between the filters at the two sites (APO and Sloan)? At any rate it unfortunately changes the counts significantly as you can see in the new commit.

**Comment by tcjansen** [comment]
Also, I thought deleting sdss/ in my local branch and pushing it here would get rid of it remotely but I guess that's not the case... what's the correct/best way of deleting folders remotely?

**Comment by bmorris3** [comment]
> Also, I thought deleting sdss/ in my local branch and pushing it here would get rid of it remotely but I guess that's not the case... what's the correct/best way of deleting folders remotely?

When you delete the files you must delete them from the command line like this: 
```
git rm sdss/*
```
This command will still work even if the `sdss/` directory is no longer there but you didn't use the `git` prefix when you `rm`'ed the files.

**Comment by bmorris3** [comment]
> Woah, so upon implementing download_file (which works well, yay), I noticed that the SDSS transmissions from SVO are much different from those provided by APO... Is this due to some physical difference between the filters at the two sites (APO and Sloan)? At any rate it unfortunately changes the counts significantly as you can see in the new commit.

Sloan filters should be standardized, so the difference between the SVO files and the ones you had downloaded from the Sloan webpage may be problematic (not your fault, of course). 

How much do the counts change? You can drag and drop a copy of the figure file into this thread for ease of chatting about it.

**Comment by bmorris3** [comment]
Hmm so I see the difference, it appears to be the difference between the "prime" filters and the not-prime filters.  The SVO filter service has the ["not-prime" profiles](http://svo2.cab.inta-csic.es/theory/fps/index.php?mode=browse&gname=SLOAN) that look like this
![image](https://user-images.githubusercontent.com/3497584/58999414-8fef4400-87ba-11e9-83f0-ca8cb5843eb1.png)
whereas the [primed filters look like this](http://filters.apo.nmsu.edu/curves/SDSS/)
![image](https://user-images.githubusercontent.com/3497584/58999499-f1171780-87ba-11e9-9217-172c459f6f15.png)

**Comment by bmorris3** [comment]
I don't fully understand the difference between the two but I think [there _is_ a difference](https://arxiv.org/pdf/astro-ph/0608575.pdf).

**Comment by bmorris3** [comment]
Ah! It looks like the history is [spelled out here](http://classic.sdss.org/dr7/algorithms/fluxcal.html).

**Comment by bmorris3** [comment]
Ok, I think the thing to do is this: 
* in the mean time, use `download_file` to get the files from the links on [this webpage](http://filters.apo.nmsu.edu/curves/SDSS/) for the primed filters for now
* Write an email to svo-support@cab.inta-csic.es with a link to the above website and say something to the effect of "hi, we need these transmission curves added please and thank you [link]". CC me on that email, I hope to see they're responsive!

**Comment by tcjansen** [comment]
Hmm, I think I'm misunderstanding something about how to download files. When I copy the link from the APO website and try:
```
sdss = ['r', 'z']  # only want r- and z-bands for now
apo_sdss_link = 'http://filters.apo.nmsu.edu/curves/SDSS/'

bandpasses = {}
for band in sdss:
    local_path = download_file(apo_sdss_link + band + '.dat')
    bp = SpectralElement.from_file(local_path)
```
I get a 404 error. I also tried the ftp protocol, which timed out. Got any more hints?

**Comment by tcjansen** [comment]
(also thanks for your investigation into the filters problem!)

**Comment by bmorris3** [comment]
The problem is the link is close but not quite right. You're looking for r.dat and z.dat under: http://filters.apo.nmsu.edu/data/SDSS/

**Comment by tcjansen** [comment]
Ah! Thank you. Silly.

Hopefully you saw that I emailed SVO. In the meantime I'll query from SDSS as suggested.

**Comment by bmorris3** [comment]
Little update for the thread, [SVO has been updated to include SDSS primed filters](http://svo2.cab.inta-csic.es/theory/fps/index.php?mode=browse&gname=SLOAN)! 🎉
