### ISSUE TITLE
Enhancement: License

### ISSUE THREAD

**Issue by bmorris3** [tcjansen/GSoC#10]
Open source code isn't technically open source until you've assigned an open source license to the repository. Please add the [BSD 3-clause license](https://github.com/astropy/astropy-tutorials/blob/master/metadata.cfg#L6) to this repo ([see here for a shortcut on how to do this!](https://help.github.com/en/articles/adding-a-license-to-a-repository#including-an-open-source-license-in-your-repository)).

**Comment by bmorris3** [comment]
See astropy/astropy-tutorials#371 for progress on getting a license in the target repo.

**Comment by tcjansen** [comment]
Done
