### ISSUE TITLE
Enhancement: Adding Kepler to tutorial

### ISSUE THREAD

**Issue by bmorris3** [tcjansen/GSoC#3]
Since we'll have PHOENIX model spectra of HAT-P-11 and TRAPPIST-1, it would be fun to model their count rates through a second telescope 🔭 . I'm thinking perhaps we can use Kepler, since (1) Kepler observed both HAT-P-11 (Kepler) and TRAPPIST-1 (K2); (2) it's a space telescope and therefore shouldn't depend on our atmosphere model, making it a good sanity check. 

Here's some of the info you'll need to do Kepler: 
* [Kepler instrument+filter response](https://keplergo.arc.nasa.gov/kepler_response_hires1.txt) – remember to use [`astropy.units.data.download_file`](http://docs.astropy.org/en/stable/api/astropy.utils.data.download_file.html) to grab this file rather than including it in the PR
* Answer key [via MAST](https://mast.stsci.edu/portal/Mashup/Clients/Mast/Portal.html): HAT-P-11 measured counts: 2.8e6 e-/s; TRAPPIST-1 measured counts: 5.70e3 e-/s
* Kepler Gain (which you might not need since we're reporting e-/s above): 110 e-/ADU ([source](https://archive.stsci.edu/kepler/manuals/KSCI-19033-001.pdf))

**Comment by tcjansen** [comment]
Think we should do this in the same tutorial or a separate tutorial? I'm leaning towards putting it in the same one.

**Comment by bmorris3** [comment]
I vote same one! 🗳

**Comment by bmorris3** [comment]
This looks great!
